name:                lambda-talk
version:             0.1.0.0
github:              "Zankoku-Okuno/lambda-talk"
license:             BSD3
author:              "Okuno Zankoku"
maintainer:          "zankoku.okuno@gmail.com"
copyright:           "Okuno Zankoku"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Zankoku-Okuno/lambda-talk#readme>

default-extensions:
- OverloadedStrings
- ScopedTypeVariables
- DataKinds
- TypeOperators
- TypeApplications

dependencies:
- base >= 4.7 && < 5
- reflex ==0.5.*
- reflex-dom ==0.4.*
- text ==1.2.*

library:
  source-dirs: src

executables:
  lambda-talk-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-talk

tests:
  lambda-talk-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambda-talk
